title: gesyn
logo: /content/lectures/files/logo.png
description: "Materials for GESIS course <i>Synthetic Data: Generation and Evaluation</i>."
theme: jekyll-theme-minimal
github:
    is_project_page: false
